- name: install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - haproxy

- name: generate haproxe.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: 
    - "haproxy restart"
