- name: install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - vim
    - screen
    - htop
    - unattended-upgrades

- name: security upgrade
  shell: "unattended-upgrade"
