- name: install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - qemu-kvm
    - libvirt-bin
    - bridge-utils
    - virtinst
    - cloud-init
    - cloud-image-utils
